version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
  mailhog:
    image: mailhog/mailhog
    ports: ["1025:1025","8025:8025"]
  quarkus:
    build: ./backend-quarkus
    depends_on: ["postgres","mailhog"]
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/authdb
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
    ports: ["8080:8080"]
